pr for Cai's feedback
play-co/svs-default-story-generator pull request #1
Opened 2022-05-16 21:12 UTC by dotmilk

2022-05-17 00:30 UTC, cainaleaouk commented
As per the list:
1) @dotmilk done it (not sure if we want it to be only those 3 colours but that fixes it for now);

2) @dotmilk done it;

3) Done. But note that characters in the cms are in the wrong path, they should be behind `/defaultcast` and they are in the root. So I fixed it to work for now and left a comment to how to fix when the cms is updated;

4) Temp fix. We don't have the BGs in the CDN nor we (or I) know what background belongs to each story. So I just set the default to point to the 1 test BG I have in my test CDN.

5) Done. Added tests for it as well

2022-05-17 00:53 UTC, dotmilk commented
@cainaleaouk not sure how you fixed #3 however, everything should be using the passed in "cdnBaseUrl" as seen [here](https://github.com/play-co/svs-default-story-generator/blob/a26cb7427b5ed22d426b716c6af241cebe4d94c9/test/index.test.ts#L163) in the tests. Which is exactly how the calling code mukunda will be using will do it, he will just have two different urls one for staging and one for prod

2022-05-17 22:58 UTC, dragonworx requested changes

2022-05-17 22:58 UTC, dragonworx commented on test/index.test.ts
> +const writeOutput = true;
This should be `false`, please change it or files will be generated by the consumer, it's only for local testing with the aim to keep it `false` in prod.

I will update it soon to be based on an ENV variable to avoid this situation again.

2022-05-17 22:58 UTC, dragonworx commented on src/index.ts
> +  const colors = ["red", "green", "blue"];
We have the real color info available in the `getCommunity(contractAddress: string)` function from `processing.ts`. Since we have the `character.contractAddress` available below we should be using that.

2022-05-18 00:40 UTC, dragonworx approved these changes

2022-05-18 00:43 UTC, achamas-playco approved these changes

2022-05-18 00:44 UTC, merged